name: RANDOM_JOKE_DEPLOY

on:
   pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
          npm install
    - run: |
        git config --global user.name "adefemi171"
        git config --global user.email "adefemi171@gmail.com"
        git add -A
    - name: Login to heroku and deploy
      uses: akhileshns/heroku-deploy@v3.8.9
      with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "chuck-joke-backend"
          heroku_email: $ {{ secrets.USER_EMAIL }}
      run: heroku git:remote -a chuck-joke-backend