name: RANDOM_JOKE_DEPLOY

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "chuck-joke-backend"
          heroku_email: $ {{ secrets.USER_EMAIL }}